### ISSUE TITLE
Where to Watch logo is too big on mobile devices

### ISSUE THREAD

**Issue by mdubus** [meilisearch/demo-movies#327]
The `Where to Watch` logo currently has the same size on Desktop and on Mobile (around 250px), but this is too big for the mobile devices. The size on mobile should be `180px`.

Current behavior:

<img width="408" alt="Capture d’écran 2022-09-14 à 09 13 46" src="https://user-images.githubusercontent.com/30866152/190086299-3887c2c9-8e39-45de-aa1e-1280c126e4ec.png">

What we expect:

<img width="306" alt="Capture d’écran 2022-09-14 à 09 10 33" src="https://user-images.githubusercontent.com/30866152/190086347-907739e2-bf87-45b0-bf01-981e24f6583f.png">

**Comment by sushantgwr87** [comment]
Is this issue still open or fixed? Asking because there is a commit regarding it in header>index.js file.

**Comment by EshaanAgg** [comment]
If this issue is still open, I would love to work on this.
