### ISSUE TITLE
Fix bug during the search by upgrading to Meilisearch v0.28.1 (at least)

### ISSUE THREAD

**Issue by curquiza** [meilisearch/demo-movies#329]
I open this issue to ensure we don't forget it, I already discussed it with @mdubus.

Since a [pretty annoying bug](https://github.com/meilisearch/meilisearch/issues/2701) during the search is present in v0.28.0, I recommend upgrading Meilisearch to v0.28.1 or later.

**Comment by Strift** [comment]
We've now upgraded to Meilisearch v1.0 =)
