### ISSUE TITLE
Remove the `attributesToHighlight` search parameter

### ISSUE THREAD

**Issue by mdubus** [meilisearch/demo-movies#336]
We currently specify the `attributesToHighlight` search parameter in the code, but since we don't highlight any attribute on search in the demo, we can remove it.

To learn more about the `attributesToHighlight` search parameter:
[https://docs.meilisearch.com/reference/api/search.html#attributes-to-highlight](https://docs.meilisearch.com/reference/api/search.html#attributes-to-highlight
)

**Comment by island-coder** [comment]
@mdubus can you check my PR? thanks!
