### ISSUE TITLE
Cannot run local build

### ISSUE THREAD

**Issue by mitar** [meilisearch/demo-movies#365]
**Description**

When I run `npm run build` after `npm install` I get:

```> where-to-watch@0.1.0 build
> next build

info  - Linting and checking validity of types  
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /home/mitar/Temp/demo-movies/.babelrc
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[=   ] info  - Generating static pages (3/4)
Error occurred prerendering page "/en". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Error serializing `.host` returned from `getStaticProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```

**Expected behavior**

That build completes successfully.

**Environment (please complete the following information):**

Node v16.17.1, npm 8.15.0, on Linux. Cloned at 44d59a0cf3001748f44a28fb743143e33353b24b.

**Comment by mdubus** [comment]
Hello @mitar 👋 

Thanks a lot for your issue. Have you tried to rename the `.env.test` file into `.env`? This error means that it couldn't find the `host` that should be provided as an environment variable.

Don't hesitate to tell me if it fixes it 😉

Have a nice day ✨

**Comment by mitar** [comment]
Awesome. This was it. But now everything is empty, no movies anywhere?

**Comment by mdubus** [comment]
Just answered it here, I think it will answer your questions ;) 
[https://github.com/meilisearch/demo-movies/issues/366](https://github.com/meilisearch/demo-movies/issues/366)
