### ISSUE TITLE
Where is data?

### ISSUE THREAD

**Issue by mitar** [meilisearch/demo-movies#366]
I would like to experiment with the search a bit and run it locally, but I do not get where the data is for my local copy? It looks like it connects to the remote API endpoint?

**Comment by mdubus** [comment]
Hello @mitar 👋

As the dataset is updated every day and is quite big, we cannot upload it here on this repository. 
To have data to play with the search, you can run a Meilisearch locally and add documents. You can find movie samples inside the `cypress/fixtures` folder if you want to look at them. 

I'll probably update the readme and add some script to populate your Meilisearch locally in the following days, to solve this problem.
Thanks again for reporting this problem 🙏

Have a nice day! ✨

**Comment by mitar** [comment]
I see. Thanks! I will wait for the script then!

**Comment by mdubus** [comment]
Hello @mitar 👋

The script has been added to the project, you can follow the Readme to know how to make it work 😉

Hope this helps, and thanks again for the issue-suggestion ✨ 🦕

**Comment by mitar** [comment]
Thanks! But this setup script just loads the small fixture subset, no? That is different from what is available at https://where2watch.meilisearch.com/ ? Is there a script you use to populate that site?

**Comment by mdubus** [comment]
Hello @mitar 👋

Yet the script populates your Meilisearch instance with a small set of data. As previously said, we can't provide here the entire database as it is too heavy + updated every day 😉

**Comment by mitar** [comment]
I understand that the dump might be large, but what about the script to do so locally?

**Comment by mitar** [comment]
Thanks.
