### ISSUE TITLE
Rename environment variables to include `Meilisearch` in it

### ISSUE THREAD

**Issue by mdubus** [meilisearch/demo-movies#373]
Currently, we have two environment variables that are being used:

- `HOST`
- `API_KEY`

We would like to rename them and include `Meilisearch` in it to avoid confusion. 

They should be renamed as follow:

- `MEILISEARCH_HOST`
- ~~MEILISEARCH_MASTER_KEY~~ -> `MEILISEARCH_API_KEY`

Make sure to rename them everywhere (code, Readme, tests, environment files, ...)

⚠ Once it's done, a maintainer must update the credentials on Vercel

**Comment by Utkarsh212** [comment]
Please assign the issue to me so that I can try working on it

**Comment by mdubus** [comment]
Hello @Utkarsh212 👋

We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages volunteer contributors to open a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](https://github.com/meilisearch/.github/blob/main/Hacktoberfest_2022_contributors_guidelines.md).
We are looking forward to reviewing your PR.

**Comment by Smartmind12** [comment]
@mdubus Kindly Review the changes in PR and send recommendations ...thanks!

**Comment by mdubus** [comment]
Fixed in #376
