### ISSUE TITLE
image not available

### ISSUE THREAD

**Issue by deepin1506** [meilisearch/demo-movies#374]
**Description**

in the movei "the greatest beer run ever" the image of actor "Ruby Ashbourne Serkis" is not loaded.

**Expected behavior**
the image was expected to be there whereas a blank circle appeared.

**Current behavior**
blank circle with no information appeared.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**

- Browser: [e.g. Chrome version 90.0]

i would love to add the image and the code for thaata

**Comment by mdubus** [comment]
Hi @deepin1506 👋

First of all, thank you for your issue. 
Our `demo-movies` database is hosted on our side, so, unfortunately, I cannot share the credentials publicly for you to push the changes. I'm sure you'll understand it 😉

But don't worry, we have a script on our side that runs every day and fetches the new movies & updates from TMDB, and send them to our database. As the movie is quite recent, I'm sure TMDB will have an update for this person's poster very soon, and everything should go to normal. So just wait & see ✨

Have a nice day!
