### ISSUE TITLE
Change white mode (sun) icon

### ISSUE THREAD

**Issue by mdubus** [meilisearch/demo-movies#89]
Currently, the Toggle has a yellow circle as a `toggle to light mode` icon:

<img width="83" alt="Capture d’écran 2022-09-14 à 10 18 58" src="https://user-images.githubusercontent.com/30866152/190100651-173a7ad6-23cd-467c-96b5-abf4b70b9887.png">

 This doesn't speak for itself, so we would like to update it. Here is the new icon:
![sun-fill](https://user-images.githubusercontent.com/30866152/190100708-cde13be4-4579-4f24-93ee-dfc725914840.svg)

It has to be placed inside the `src/components/icons/svg` folder, and then simply run the `yarn icons` command to transform the SVG into a React component.

**Comment by nooras** [comment]
Hi I wanted to work on this issue
can you please assign it to me @mdubus ?

**Comment by nooras** [comment]
#self-assign

**Comment by nooras** [comment]
Hi @mdubus 
I made changes for White mode Sun Icon. I created Pull request. for this issue. Please find below Screenshots.

![image](https://user-images.githubusercontent.com/30138146/193453311-dcdec62a-7ce1-474d-bfff-26eaf313e603.png)

Full screenshot
![image](https://user-images.githubusercontent.com/30138146/193452885-5405aa84-3c4a-43a4-8215-9e2f20846e32.png)

Let me know if any changes are required.
Thanks :)
